# Generated by Django 4.2.9 on 2024-01-31 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notes',
            name='slug',
            field=models.SlugField(default='', max_length=255, unique=True),
        ),
    ]
